;;; Commentary: Do not edit this file. Editing this file breaks the update
;; mechanism. Use config/custom-init.el instead.

;;; Code:

(when (< emacs-major-version 27)
  (package-initialize))

(setq package-archives '(("gnu" . "https://elpa.gnu.org/packages/")
                         ("marmalade" . "https://marmalade-repo.org/packages/")
                         ("melpa-stable" . "https://stable.melpa.org/packages/")
                         ("melpa" . "https://melpa.org/packages/")))

(setq package-archive-priorities
      '(("melpa-stable" . 20)
        ("marmalade" . 20)
        ("gnu" . 10)
        ("melpa" . 0)))

(setq inhibit-startup-message t)

(unless (package-installed-p 'f)
  (package-refresh-contents)
  (package-install 'f))

(require 'f)
(defvar gears-emacs-basepath (f-dirname (f-this-file))
  "Location of the installation.")

(unless (f-dir? (concat gears-emacs-basepath "/config"))
  (f-mkdir (concat gears-emacs-basepath "/config")))

(setq custom-file (concat gears-emacs-basepath "/config/custom.el"))

(when (f-file? (concat gears-emacs-basepath "/config/custom.el"))
  (load custom-file))

;; Check for the layers config file
(if (f-file? (concat gears-emacs-basepath "/config/layers.el"))
    ;; Load if it exists
    (load (concat gears-emacs-basepath "/config/layers"))
  (progn
    ;; Create a new file if it does not exist.

    (f-write-text "(setq gears-layer-installed-list '())"
                  'utf-8
                  (concat gears-emacs-basepath "/config/layers.el"))
    (load (concat gears-emacs-basepath "/config/layers"))))

(unless (> (length gears-layer-installed-list) 0)
  (load "~/.emacs.d/functions/install")

  (gears-install-firstrun-setup))

(load (concat gears-emacs-basepath "/functions/update"))
(load (concat gears-emacs-basepath "/functions/layers"))
(load (concat gears-emacs-basepath "/functions/helper"))
(gears-layers-init)

(when (f-file? (concat gears-emacs-basepath "/config/custom-init.el"))
  (load (concat gears-emacs-basepath "/config/custom-init")))

;;; init.el ends here
