;;; Commentary: Do not edit this file. Editing this file breaks the update
;; mechanism. Use config/custom-init.el instead.

;;; Code:

(package-initialize)

(setq package-archives '(("gnu" . "https://elpa.gnu.org/packages/")
                         ("marmalade" . "https://marmalade-repo.org/packages/")
                         ("melpa" . "https://melpa.org/packages/")))

(setq inhibit-startup-message t)

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(unless (package-installed-p 'f)
  (use-package f
    :ensure t))

(require 'f)
(defvar gears-emacs-basepath (f-dirname (f-this-file)))

(unless (f-dir? (concat gears-emacs-basepath "/config"))
  (f-mkdir (concat gears-emacs-basepath "/config")))

(setq custom-file (concat gears-emacs-basepath "/config/custom.el"))

(when (f-file? (concat gears-emacs-basepath "/config/custom.el"))
    (load custom-file))

(if (f-file? (concat gears-emacs-basepath "/config/layers.el"))
    (load (concat gears-emacs-basepath "/config/layers"))
  (progn (f-write-text "(setq gears-layer-installed-list '())"
                       'utf-8
                       (concat gears-emacs-basepath "/config/layers.el"))
         (load (concat gears-emacs-basepath "/config/layers"))))

(unless (> (length gears-layer-installed-list) 0)
  (load "~/.emacs.d/functions/install")

  (gears-install-firstrun-setup))

(load (concat gears-emacs-basepath "/functions/update"))
(load (concat gears-emacs-basepath "/functions/layers"))
(gears-layers-init)

(if (f-file? (concat gears-emacs-basepath "/config/custom-init.el"))
    (load (concat gears-emacs-basepath "/config/custom-init")))

;;; init.el ends here
